# Generated by Django 5.1.15 on 2026-04-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField()),
                ('language', models.CharField(default='javascript', max_length=30)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_question', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snapshots', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
