# Generated by Django 5.1.7 on 2026-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_codesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="company",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
